import { useState, useMemo } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { ScrollArea } from "@/components/ui/scroll-area";
import { useToast } from "@/hooks/use-toast";
import { AlertCircle, CheckCircle2 } from "lucide-react";
import type { ProductOption } from "@shared/schema";

interface AutoGenerateDialogProps {
  productId: string;
  isOpen: boolean;
  onClose: () => void;
}

interface VariantCombination {
  title: string;
  option1: string | null;
  option2: string | null;
  option3: string | null;
}

export function AutoGenerateDialog({
  productId,
  isOpen,
  onClose,
}: AutoGenerateDialogProps) {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [defaultPrice, setDefaultPrice] = useState("0.00");
  const [isGenerating, setIsGenerating] = useState(false);
  const [progress, setProgress] = useState({ current: 0, total: 0 });

  // Fetch options
  const { data: options = [] } = useQuery<ProductOption[]>({
    queryKey: ["options", productId],
    queryFn: async () => {
      const res = await fetch(`/api/products/${productId}/options`, {
        credentials: "include",
      });
      if (!res.ok) throw new Error("Failed to fetch options");
      return res.json();
    },
    enabled: isOpen,
  });

  // Fetch existing variants (to skip duplicates)
  const { data: existingVariants = [] } = useQuery({
    queryKey: ["variants", productId],
    queryFn: async () => {
      const res = await fetch(`/api/products/${productId}/variants`, {
        credentials: "include",
      });
      if (!res.ok) throw new Error("Failed to fetch variants");
      return res.json();
    },
    enabled: isOpen,
  });

  // Generate all variant combinations
  const combinations = useMemo(() => {
    if (options.length === 0) return [];

    const sortedOptions = [...options].sort((a, b) => a.position - b.position);

    const results: VariantCombination[] = [];

    function generate(current: (string | null)[], depth: number) {
      if (depth === 3) {
        // Always generate 3 levels (null for missing options)
        const title = current.filter(Boolean).join(" / ");
        results.push({
          title,
          option1: current[0] || null,
          option2: current[1] || null,
          option3: current[2] || null,
        });
        return;
      }

      const option = sortedOptions[depth];
      if (option) {
        // This option exists - iterate through its values
        for (const value of option.values) {
          generate([...current, value], depth + 1);
        }
      } else {
        // This option doesn't exist - use null
        generate([...current, null], depth + 1);
      }
    }

    generate([], 0);
    return results;
  }, [options]);

  // Filter out combinations that already exist
  const newCombinations = useMemo(() => {
    const existingSet = new Set(
      existingVariants.map((v: any) =>
        `${v.option1 || ''}|${v.option2 || ''}|${v.option3 || ''}`
      )
    );

    return combinations.filter((combo) => {
      const key = `${combo.option1 || ''}|${combo.option2 || ''}|${combo.option3 || ''}`;
      return !existingSet.has(key);
    });
  }, [combinations, existingVariants]);

  // Generate variants mutation
  const generateMutation = useMutation({
    mutationFn: async () => {
      setIsGenerating(true);
      setProgress({ current: 0, total: newCombinations.length });

      const created = [];
      const errors = [];

      for (let i = 0; i < newCombinations.length; i++) {
        const combo = newCombinations[i];
        setProgress({ current: i + 1, total: newCombinations.length });

        try {
          const res = await fetch(`/api/products/${productId}/variants`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            credentials: "include",
            body: JSON.stringify({
              ...combo,
              price: defaultPrice,
              inventoryQuantity: 0,
            }),
          });

          if (res.ok) {
            created.push(await res.json());
          } else if (res.status === 400) {
            // Duplicate - skip silently
          } else {
            errors.push(combo.title);
          }
        } catch (error) {
          errors.push(combo.title);
        }
      }

      setIsGenerating(false);
      return { created, errors };
    },
    onSuccess: ({ created, errors }) => {
      queryClient.invalidateQueries({ queryKey: ["variants", productId] });

      if (errors.length === 0) {
        toast({
          title: "Variants generated",
          description: `Created ${created.length} new variants`,
        });
      } else {
        toast({
          title: "Partially completed",
          description: `Created ${created.length} variants, ${errors.length} failed`,
          variant: "destructive",
        });
      }

      onClose();
      setDefaultPrice("0.00");
    },
    onError: (error: Error) => {
      setIsGenerating(false);
      toast({
        title: "Failed to generate variants",
        description: error.message,
        variant: "destructive",
      });
    },
  });

  const handleGenerate = () => {
    // Validate price
    const numPrice = parseFloat(defaultPrice);
    if (isNaN(numPrice) || numPrice < 0) {
      toast({
        title: "Invalid price",
        description: "Please enter a valid price (0 or greater)",
        variant: "destructive",
      });
      return;
    }

    // Confirm if generating many variants
    if (newCombinations.length > 50) {
      if (!confirm(`This will create ${newCombinations.length} new variants. Continue?`)) {
        return;
      }
    }

    generateMutation.mutate();
  };

  const handleClose = () => {
    if (!isGenerating) {
      onClose();
      setDefaultPrice("0.00");
    }
  };

  // Validation messages
  const canGenerate = options.length > 0 && newCombinations.length > 0 && newCombinations.length <= 100;

  return (
    <Dialog open={isOpen} onOpenChange={handleClose}>
      <DialogContent className="max-w-2xl max-h-[80vh]">
        <DialogHeader>
          <DialogTitle>Auto-generate variants</DialogTitle>
          <DialogDescription>
            Create all possible variant combinations from your product options
          </DialogDescription>
        </DialogHeader>

        {options.length === 0 ? (
          <div className="py-8 text-center">
            <AlertCircle className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
            <p className="text-sm text-muted-foreground">
              No options defined. Create product options first.
            </p>
          </div>
        ) : newCombinations.length === 0 ? (
          <div className="py-8 text-center">
            <CheckCircle2 className="h-12 w-12 text-green-500 mx-auto mb-4" />
            <p className="text-sm text-muted-foreground">
              All possible variants already exist for this product.
            </p>
            <p className="text-xs text-muted-foreground mt-2">
              Total combinations: {combinations.length}
            </p>
          </div>
        ) : newCombinations.length > 100 ? (
          <div className="py-8 text-center">
            <AlertCircle className="h-12 w-12 text-destructive mx-auto mb-4" />
            <p className="text-sm text-muted-foreground">
              Cannot generate more than 100 variants per product.
            </p>
            <p className="text-xs text-muted-foreground mt-2">
              This would create {newCombinations.length} variants.
            </p>
            <p className="text-xs text-muted-foreground mt-2">
              Reduce the number of options or option values.
            </p>
          </div>
        ) : (
          <div className="space-y-4">
            {/* Summary */}
            <div className="bg-muted p-4 rounded-lg">
              <p className="text-sm font-medium mb-2">
                This will create <span className="text-primary font-bold">{newCombinations.length}</span> new variants:
              </p>
              {existingVariants.length > 0 && (
                <p className="text-xs text-muted-foreground">
                  ({combinations.length - newCombinations.length} variants already exist and will be skipped)
                </p>
              )}
            </div>

            {/* Default Price */}
            <div>
              <Label htmlFor="defaultPrice">Default price for all variants</Label>
              <Input
                id="defaultPrice"
                type="text"
                value={defaultPrice}
                onChange={(e) => setDefaultPrice(e.target.value)}
                placeholder="0.00"
                disabled={isGenerating}
              />
            </div>

            {/* Preview List */}
            <div>
              <Label className="text-xs text-muted-foreground mb-2">Preview</Label>
              <ScrollArea className="h-[200px] border rounded-md p-4">
                <div className="space-y-1">
                  {newCombinations.slice(0, 50).map((combo, index) => (
                    <div key={index} className="text-sm">
                      {index + 1}. {combo.title}
                    </div>
                  ))}
                  {newCombinations.length > 50 && (
                    <div className="text-sm text-muted-foreground italic">
                      ... and {newCombinations.length - 50} more
                    </div>
                  )}
                </div>
              </ScrollArea>
            </div>

            {/* Progress */}
            {isGenerating && (
              <div>
                <div className="flex justify-between text-sm mb-2">
                  <span>Creating variants...</span>
                  <span>{progress.current} / {progress.total}</span>
                </div>
                <div className="w-full bg-muted rounded-full h-2">
                  <div
                    className="bg-primary h-2 rounded-full transition-all duration-300"
                    style={{
                      width: `${(progress.current / progress.total) * 100}%`,
                    }}
                  />
                </div>
              </div>
            )}

            {/* Warning */}
            <div className="bg-yellow-50 border border-yellow-200 p-3 rounded-md">
              <p className="text-xs text-yellow-800">
                <strong>Note:</strong> Existing variants will not be replaced or modified.
              </p>
            </div>
          </div>
        )}

        <DialogFooter>
          <Button
            variant="outline"
            onClick={handleClose}
            disabled={isGenerating}
          >
            Cancel
          </Button>
          <Button
            onClick={handleGenerate}
            disabled={!canGenerate || isGenerating}
          >
            {isGenerating
              ? "Generating..."
              : `Generate ${newCombinations.length} variant${newCombinations.length === 1 ? "" : "s"}`}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
