import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { DndContext, closestCenter, DragEndEvent } from "@dnd-kit/core";
import { SortableContext, verticalListSortingStrategy } from "@dnd-kit/sortable";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Plus, Table, Wand2, Upload, Database } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { useLocation } from "wouter";
import { OptionRow } from "./OptionRow";
import { AddOptionDialog } from "./AddOptionDialog";
import { GroupedVariantList } from "./GroupedVariantList";
import { AutoGenerateDialog } from "./AutoGenerateDialog";
import { QBImportDialog } from "./QBImportDialog";
import { QBImportModal } from "@/components/QBImportModal";
import type { ProductOption, Product } from "@shared/schema";

interface UnifiedVariantsCardProps {
  productId: string;
  product?: Product;
}

export function UnifiedVariantsCard({ productId, product }: UnifiedVariantsCardProps) {
  const { toast } = useToast();
  const queryClient = useQueryClient();
  const [, setLocation] = useLocation();
  const [showAddDialog, setShowAddDialog] = useState(false);
  const [showAutoGenerate, setShowAutoGenerate] = useState(false);
  const [showQBImport, setShowQBImport] = useState(false);
  const [showQBDatabaseImport, setShowQBDatabaseImport] = useState(false);

  // Fetch options
  const { data: options = [], isLoading } = useQuery<ProductOption[]>({
    queryKey: ["options", productId],
    queryFn: async () => {
      const res = await fetch(`/api/products/${productId}/options`, {
        credentials: "include",
      });
      if (!res.ok) throw new Error("Failed to fetch options");
      return res.json();
    },
  });

  // Reorder mutation
  const reorderMutation = useMutation({
    mutationFn: async (optionIds: string[]) => {
      const res = await fetch(`/api/products/${productId}/options/reorder`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        credentials: "include",
        body: JSON.stringify({ optionIds }),
      });
      if (!res.ok) throw new Error("Failed to reorder");
      return res.json();
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["options", productId] });
      toast({ title: "Options reordered" });
    },
    onError: () => {
      toast({ title: "Failed to reorder", variant: "destructive" });
    },
  });

  // Handle drag end
  const handleDragEnd = (event: DragEndEvent) => {
    const { active, over } = event;
    if (!over || active.id === over.id) return;

    const oldIndex = options.findIndex((o) => o.id === active.id);
    const newIndex = options.findIndex((o) => o.id === over.id);

    const newOrder = [...options];
    const [removed] = newOrder.splice(oldIndex, 1);
    newOrder.splice(newIndex, 0, removed);

    // Optimistically update UI
    queryClient.setQueryData(["options", productId], newOrder);

    // Save to server
    reorderMutation.mutate(newOrder.map((o) => o.id));
  };

  // Fetch variant count from API
  const { data: variantCount = 0 } = useQuery<number>({
    queryKey: ["variantCount", productId],
    queryFn: async () => {
      const res = await fetch(`/api/products/${productId}/variants/count`, {
        credentials: "include",
      });
      if (!res.ok) return 0;
      const data = await res.json();
      return data.count;
    },
  });

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <div>
            <CardTitle>Variants</CardTitle>
            <CardDescription>
              {variantCount > 0
                ? `${variantCount} variant(s)`
                : "Add options to create variants for this product"}
            </CardDescription>
          </div>
          <div className="flex items-center gap-2">
            {/* QuickBooks Database Import Button (NEW - search QB inventory) */}
            <Button
              variant="outline"
              size="sm"
              onClick={() => setShowQBDatabaseImport(true)}
            >
              <Database className="mr-2 h-4 w-4" />
              Import from QB
            </Button>
            {/* QuickBooks File Import Button (legacy - file upload) */}
            {product?.styleNumber && (
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setShowQBImport(true)}
                title="Import from QB file (legacy)"
              >
                <Upload className="h-4 w-4" />
              </Button>
            )}
            {/* Bulk Edit Button */}
            {variantCount > 1 && (
              <Button
                variant="outline"
                size="sm"
                onClick={() => setLocation(`/products/${productId}/bulk-edit`)}
              >
                <Table className="mr-2 h-4 w-4" />
                Bulk edit
              </Button>
            )}
          </div>
        </div>
      </CardHeader>

      <CardContent className="space-y-6">
        {/* OPTIONS SECTION */}
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-medium">Options</h3>
            {options.length < 3 && (
              <Button
                variant="outline"
                size="sm"
                onClick={() => setShowAddDialog(true)}
              >
                <Plus className="mr-2 h-4 w-4" />
                Add option
              </Button>
            )}
          </div>

          {isLoading ? (
            <div className="text-center py-8 text-muted-foreground text-sm">
              Loading options...
            </div>
          ) : options.length === 0 ? (
            <div className="text-center py-8 text-muted-foreground text-sm">
              No options yet. Add your first option to create variants.
            </div>
          ) : (
            <DndContext
              collisionDetection={closestCenter}
              onDragEnd={handleDragEnd}
            >
              <SortableContext
                items={options.map((o) => o.id)}
                strategy={verticalListSortingStrategy}
              >
                {options.map((option) => (
                  <OptionRow
                    key={option.id}
                    option={option}
                    productId={productId}
                  />
                ))}
              </SortableContext>
            </DndContext>
          )}

          {options.length > 0 && options.length < 3 && (
            <Button
              variant="ghost"
              size="sm"
              onClick={() => setShowAddDialog(true)}
              className="w-full"
            >
              <Plus className="mr-2 h-4 w-4" />
              Add another option
            </Button>
          )}
        </div>

        {/* VARIANTS SECTION */}
        {options.length > 0 && (
          <>
            <div className="border-t" />
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <h3 className="text-sm font-medium">
                  {variantCount === 0
                    ? "No variants yet"
                    : `${variantCount} variant${variantCount === 1 ? '' : 's'}`
                  }
                </h3>
                {options.length > 0 && (
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => setShowAutoGenerate(true)}
                  >
                    <Wand2 className="mr-2 h-4 w-4" />
                    Auto-generate variants
                  </Button>
                )}
              </div>
              <GroupedVariantList productId={productId} />
            </div>
          </>
        )}
      </CardContent>

      <AddOptionDialog
        productId={productId}
        isOpen={showAddDialog}
        onClose={() => setShowAddDialog(false)}
        currentPosition={options.length + 1}
      />

      <AutoGenerateDialog
        productId={productId}
        isOpen={showAutoGenerate}
        onClose={() => setShowAutoGenerate(false)}
      />

      <QBImportDialog
        productId={productId}
        open={showQBImport}
        onOpenChange={setShowQBImport}
      />

      <QBImportModal
        productId={productId}
        open={showQBDatabaseImport}
        onOpenChange={setShowQBDatabaseImport}
        onImportComplete={() => {
          // Refresh options and variants after import
          queryClient.invalidateQueries({ queryKey: ["options", productId] });
          queryClient.invalidateQueries({ queryKey: ["variants", productId] });
          queryClient.invalidateQueries({ queryKey: ["variantCount", productId] });
          queryClient.invalidateQueries({ queryKey: [`/api/products/${productId}`] });
        }}
      />
    </Card>
  );
}
