import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Plus, Wand2, CheckSquare } from "lucide-react";
import { VariantRow } from "./VariantRow";
import { VariantRowExpanded } from "./VariantRowExpanded";
import { BulkActionsBar } from "./BulkActionsBar";
import { AutoGenerateDialog } from "./AutoGenerateDialog";
import { VariantEditorDialog } from "./VariantEditorDialog";
import type { ProductOption, ProductVariant } from "@shared/schema";

interface VariantListProps {
  productId: string;
}

export function VariantList({ productId }: VariantListProps) {
  // State
  const [selectedIds, setSelectedIds] = useState<string[]>([]);
  const [selectionMode, setSelectionMode] = useState(false);
  const [expandedIds, setExpandedIds] = useState<Set<string>>(new Set());
  const [showAutoGenerate, setShowAutoGenerate] = useState(false);
  const [showAddVariant, setShowAddVariant] = useState(false);
  const [editingVariantId, setEditingVariantId] = useState<string | null>(null);

  // Fetch options (needed for auto-generation)
  const { data: options = [] } = useQuery<ProductOption[]>({
    queryKey: ["options", productId],
    queryFn: async () => {
      const res = await fetch(`/api/products/${productId}/options`, {
        credentials: "include",
      });
      if (!res.ok) throw new Error("Failed to fetch options");
      return res.json();
    },
  });

  // Fetch variants
  const { data: variants = [], isLoading } = useQuery<ProductVariant[]>({
    queryKey: ["variants", productId],
    queryFn: async () => {
      const res = await fetch(`/api/products/${productId}/variants`, {
        credentials: "include",
      });
      if (!res.ok) throw new Error("Failed to fetch variants");
      return res.json();
    },
  });

  // Selection handlers
  const handleToggleSelect = (id: string) => {
    setSelectedIds((prev) =>
      prev.includes(id) ? prev.filter((i) => i !== id) : [...prev, id]
    );
  };

  const handleClearSelection = () => {
    setSelectedIds([]);
    setSelectionMode(false);
  };

  // Expand/collapse handlers
  const handleToggleExpand = (id: string) => {
    setExpandedIds((prev) => {
      const newSet = new Set(prev);
      if (newSet.has(id)) {
        newSet.delete(id);
      } else {
        // Only allow one expanded at a time
        newSet.clear();
        newSet.add(id);
      }
      return newSet;
    });
  };

  // Empty state
  if (!isLoading && variants.length === 0) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Variants</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="text-center py-12">
            <div className="text-muted-foreground mb-4">
              This product has no variants yet
            </div>
            <div className="text-sm text-muted-foreground mb-6">
              Create variants from options or add them manually
            </div>
            <div className="flex gap-2 justify-center">
              <Button
                variant="outline"
                onClick={() => setShowAutoGenerate(true)}
                disabled={options.length === 0}
              >
                <Wand2 className="mr-2 h-4 w-4" />
                Auto-generate variants
              </Button>
              <Button onClick={() => setShowAddVariant(true)}>
                <Plus className="mr-2 h-4 w-4" />
                Add variant
              </Button>
            </div>
            {options.length === 0 && (
              <div className="text-sm text-muted-foreground mt-4">
                Create product options first to auto-generate variants
              </div>
            )}
          </div>
        </CardContent>
      </Card>
    );
  }

  // Loading state
  if (isLoading) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Variants</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="text-center py-12 text-muted-foreground">
            Loading variants...
          </div>
        </CardContent>
      </Card>
    );
  }

  // Main list view
  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-4">
        <CardTitle>
          Variants ({variants.length})
        </CardTitle>
        <div className="flex gap-2">
          {!selectionMode && (
            <>
              <Button
                variant="outline"
                size="sm"
                onClick={() => setShowAutoGenerate(true)}
                disabled={options.length === 0}
              >
                <Wand2 className="mr-2 h-4 w-4" />
                Auto-generate
              </Button>
              <Button size="sm" onClick={() => setShowAddVariant(true)}>
                <Plus className="mr-2 h-4 w-4" />
                Add variant
              </Button>
            </>
          )}
          <Button
            variant={selectionMode ? "default" : "outline"}
            size="sm"
            onClick={() => {
              if (selectionMode) {
                handleClearSelection();
              } else {
                setSelectionMode(true);
              }
            }}
          >
            <CheckSquare className="mr-2 h-4 w-4" />
            {selectionMode ? "Exit selection" : "Select"}
          </Button>
        </div>
      </CardHeader>
      <CardContent>
        {/* Bulk Actions Bar */}
        {selectionMode && selectedIds.length > 0 && (
          <BulkActionsBar
            selectedIds={selectedIds}
            productId={productId}
            onClearSelection={handleClearSelection}
          />
        )}

        {/* Variant List */}
        <div className="border rounded-lg overflow-hidden">
          {variants.map((variant) => (
            <div key={variant.id}>
              <VariantRow
                variant={variant}
                productId={productId}
                isSelected={selectedIds.includes(variant.id)}
                isExpanded={expandedIds.has(variant.id)}
                selectionMode={selectionMode}
                onToggleSelect={handleToggleSelect}
                onToggleExpand={handleToggleExpand}
                onEdit={() => setEditingVariantId(variant.id)}
              />
              {expandedIds.has(variant.id) && (
                <VariantRowExpanded
                  variant={variant}
                  productId={productId}
                  onCollapse={() => handleToggleExpand(variant.id)}
                />
              )}
            </div>
          ))}
        </div>
      </CardContent>

      {/* Auto-Generate Dialog */}
      <AutoGenerateDialog
        productId={productId}
        isOpen={showAutoGenerate}
        onClose={() => setShowAutoGenerate(false)}
      />

      {/* Variant Editor Dialog */}
      <VariantEditorDialog
        productId={productId}
        variantId={editingVariantId}
        onClose={() => setEditingVariantId(null)}
      />
    </Card>
  );
}
